## Authentication with base64 encoder tool, like https://www.base64encode.org/
### Curator  
@curatorAuth = Y3VyYXRvckBzYXAuY29tOldAbGNvbWUyMDI0IQ==

###author#
@authorAuth = YXV0aG9yQHNhcC5jb206V0BsY29tZTIwMjQh

### Admin 
@adminAuth = YWRtaW5Ac2FwLmNvbTpXQGxjb21lMjAyNCE=

### get myUser for author
#
GET http://localhost:4004/odata/v4/user/User?
Authorization: Basic {{authorAuth}}

### get myUser for curator
#
GET http://localhost:4004/odata/v4/user/User?
Authorization: Basic {{curatorAuth}}

### GET Curator-assigned categories
#
GET http://localhost:4004/odata/v4/user/UserCategories?$expand=category
Authorization: Basic {{curatorAuth}}

### ADD categories to curator user (This is not working)
#
PATCH http://localhost:4004/odata/v4/user/Users?$expand=UserCategories
Authorization: Basic {{curatorAuth}}
Content-Type: application/json

{
  "UserCategories": [
    {
      "category_ID": "0fce7498-fa95-4adc-9b58-5e65357401c5",
      "user_ID": "curator@sap.com"
    }
  ]
}


###
#
POST http://localhost:4004/odata/v4/user/UserCategories
Content-Type: application/json
Authorization: Basic {{curatorAuth}}

{
  "category_ID": "0fce7498-fa95-4adc-9b58-5e65357401c5",
  "user_ID": "curator@sap.com"
}

### get CuratorLessons
#
GET http://localhost:4004/odata/v4/curate/CuratorLessons?
Authorization: Basic {{curatorAuth}}

# get myUser for curator
#
GET http://localhost:4004/odata/v4/user/User?
Authorization: Basic {{adminAuth}}

###
#
# Use actual service 
#
GET https://port4004-workspaces-ws-ts97f.us10.trial.applicationstudio.cloud.sap/sap.btp.categories/index.html 
Authorization: Basic {{curatorAuth}}

###
#
# Get User with ID admin@sap.com
#
GET http://localhost:4004/odata/v4/admin/Lessons
Authorization: Basic {{adminAuth}}
###
#
# Create User with ID 6
#
POST http://localhost:4004/odata/v4/lesson/Users?
Content-Type: application/json

{"ID": "otto.g@gmail.com", "f_name": "Otto", "l_name": "Gupta", "email": "otto.g@gmail.com", "internal": "0", "role_code": 3}

###
#
# Change User with ID otto.g@gmail.com: Email update
#
PATCH http://localhost:4004/odata/v4/lesson/Users(otto.g@gmail.com)
Content-Type: application/json

{"email": "otto.gupta@gmail.com"}

###
#
# Delete User with ID 7: 
#
DELETE http://localhost:4004/odata/v4/lesson/Users(otto.g@gmail.com)

###
#
# Create new lesson 8889
#
POST http://localhost:4004/odata/v4/lesson/lessons
Content-Type: application/json

{
  "ID": 9996,
  "classification_code" : 100,
  "title": "Test lesson 9997",
  "text": "Test text for lesson 9997",
  "author_ID": "otto.g@gmail.com",
  "status_code": 5
  // other necessary fields
}

###
#
# Read lesson 8889
#
GET http://localhost:36497/odata/v4/lesson/lessons

###
#
# Get Classifications 
# 
GET http://localhost:36539/odata/v4/admin/Classifications

###
#
# Create new Classification 500 'Endless Capabilities'
#
POST http://localhost:36539/odata/v4/admin/Classifications
Content-Type: application/json

{
  "code": 500,
  "descr": "Endless Capabilities"
}