@amAuth = YW1Ac2FwLmNvbTpBbWF6aW5nMjAyNCE=
###
#
# Browse Users
#
GET http://localhost:4004/odata/v4/lesson/Users?
Authorization: Basic {{amAuth}}

###
#
# Use actual service 
#
GET https://port4004-workspaces-ws-ts97f.us10.trial.applicationstudio.cloud.sap/sap.btp.categories/index.html 
Authorization: Basic {{amAuth}}

###
#
# Get User with ID 5
#
GET http://localhost:4004/odata/v4/lesson/Users(ID=bfc7a472-afa5-4620-960b-8d71f703df47)
Authorization: Basic {{amAuth}}
###
#
# Create User with ID 6
#
POST http://localhost:4004/odata/v4/lesson/Users?
Content-Type: application/json

{"ID": "otto.g@gmail.com", "f_name": "Otto", "l_name": "Gupta", "email": "otto.g@gmail.com", "internal": "0", "role_code": 3}

###
#
# Change User with ID otto.g@gmail.com: Email update
#
PATCH http://localhost:4004/odata/v4/lesson/Users(otto.g@gmail.com)
Content-Type: application/json

{"email": "otto.gupta@gmail.com"}

###
#
# Delete User with ID 7: 
#
DELETE http://localhost:4004/odata/v4/lesson/Users(otto.g@gmail.com)

###
#
# Create new lesson 8889
#
POST http://localhost:43159/odata/v4/lesson/lessons
Content-Type: application/json

{
  "ID": 9996,
  "classification_code" : 100,
  "title": "Test lesson 9997",
  "text": "Test text for lesson 9997",
  "author_ID": "otto.g@gmail.com",
  "status_code": 5
  // other necessary fields
}

###
#
# Read lesson 8889
#
GET http://localhost:36497/odata/v4/lesson/lessons

###
#
# Get Classifications 
# 
GET http://localhost:36539/odata/v4/admin/Classifications

###
#
# Create new Classification 500 'Endless Capabilities'
#
POST http://localhost:36539/odata/v4/admin/Classifications
Content-Type: application/json

{
  "code": 500,
  "descr": "Endless Capabilities"
}